# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
react:
  title: Zdharma Initiative
  name: Sebastian Gniazdowski
  menu_right_subtitle: Computer Scientist
  avatar: /static/img/dharma_logo.png
  logo: /static/img/logo_theme.png
  email: sgniazdowski@gmail.com
  description: > # this means to ignore newlines until "baseurl:"
    Advanced Zsh projects, e.g. ZUI – (D)HTML-like curses interface
    library, Zconvey – Zsh session integration via file locks
    and sched.
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "http://zdharma.org" # the base hostname & protocol for your site
  permalink: /posts/:title
  social:
    github: http://github.com/zdharma
    twitter: http://twitter.com/zdharmai
    facebook: http://facebook.com/zdharmai
    rss: feed.xml



title: Zdharma Initiative
name: Sebastian Gniazdowski
menu_right_subtitle: Computer Scientist
avatar: /static/img/dharma_logo.png
logo: /static/img/logo.png
email: sgniazdowski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Advanced Zsh projects, e.g. ZUI – (D)HTML-like curses interface
    library, Zconvey – Zsh session integration via file locks
    and sched.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zdharma.org" # the base hostname & protocol for your site
permalink: /posts/:title

twitter_username: zdharmai
github_username: zdharma


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

source: src
destination: public

assets:
  compress:
    css: false
    js: false

  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  cdn: zdharma.org
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true

  assets:
    - "*.png"
    - "bundle.css"
    - "bundle.js.map"
    - "*.svg"
    - "*.eof"
    - "*.ttf"

  sources:
    - src/_assets/css
    - src/_assets/fonts
    - src/_assets/img
    - src/_assets/projects

  features:
    liquid: false
    integrity: true
    automatic_img_size: true
    automatic_img_alt : true

exclude: ['node_modules', 'Gemfile', '.asset-cache', 'build-prod.sh', 'build-dev.sh']

gems:
  - jekyll-assets
  - jekyll_pages_api
  - jekyll-react
